# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: audio_stream.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'audio_stream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x61udio_stream.proto\x12\x0c\x61udio_engine\"F\n\x0b\x41udioConfig\x12\x13\n\x0bsample_rate\x18\x01 \x01(\r\x12\x10\n\x08\x63hannels\x18\x02 \x01(\r\x12\x10\n\x08\x65ncoding\x18\x03 \x01(\t\"[\n\nAudioFrame\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12)\n\x06\x63onfig\x18\x03 \x01(\x0b\x32\x19.audio_engine.AudioConfig\"\\\n\tVadResult\x12\x11\n\tis_speech\x18\x01 \x01(\x08\x12\x1a\n\x12speech_probability\x18\x02 \x01(\x02\x12\x10\n\x08start_ms\x18\x03 \x01(\x04\x12\x0e\n\x06\x65nd_ms\x18\x04 \x01(\x04\"W\n\x0eProcessedChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x14\n\x0ctimestamp_ms\x18\x02 \x01(\x04\x12\x11\n\tis_speech\x18\x03 \x01(\x08\x12\x0e\n\x06\x65nergy\x18\x04 \x01(\x02\x32\xa6\x01\n\x0e\x41udioProcessor\x12J\n\x0cProcessAudio\x12\x18.audio_engine.AudioFrame\x1a\x1c.audio_engine.ProcessedChunk(\x01\x30\x01\x12H\n\x13\x44\x65tectVoiceActivity\x12\x18.audio_engine.AudioFrame\x1a\x17.audio_engine.VadResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'audio_stream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AUDIOCONFIG']._serialized_start=36
  _globals['_AUDIOCONFIG']._serialized_end=106
  _globals['_AUDIOFRAME']._serialized_start=108
  _globals['_AUDIOFRAME']._serialized_end=199
  _globals['_VADRESULT']._serialized_start=201
  _globals['_VADRESULT']._serialized_end=293
  _globals['_PROCESSEDCHUNK']._serialized_start=295
  _globals['_PROCESSEDCHUNK']._serialized_end=382
  _globals['_AUDIOPROCESSOR']._serialized_start=385
  _globals['_AUDIOPROCESSOR']._serialized_end=551
# @@protoc_insertion_point(module_scope)
